# What is the probability of a person playing when the weather is sunny? 

In [1]:
# probality of play yes when the whether is sunny
sunny1=2
# probality of play no when the whether is sunny
sunny2=2
# probality of play yes when the whether is Overcast
overcast1=4
# probality of play no when the whether is Overcast
overcast2=0
# probality of play yes when the whether is Rainy
rainy1=2
# probality of play no when the whether is Rainy
rainy2=3
Total_yes=8
Total_no=5

#prbaility i.e p(Yes|Sunny)
A=sunny1/Total_yes
print("P(Yes|Sunny)=",A)


P(Yes|Sunny)= 0.25


# importing Libraries

In [2]:
import numpy as np
import pandas as pd


# Load datasets iris from sklearn

In [3]:
from sklearn.datasets import load_iris
data=load_iris()
x=data['data']
y=data['target']


In [4]:
from sklearn.model_selection import train_test_split as tts
train_x, test_x, train_y, test_y = tts(x, y, test_size = 0.2)

In [5]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_x, train_y)


GaussianNB(priors=None)

In [6]:
ypred = gnb.predict(test_x)


In [10]:
result=pd.DataFrame({'Actual':test_y,'Predicted':ypred})
print(result)


    Actual  Predicted
0        2          2
1        2          2
2        2          2
3        2          2
4        0          0
5        2          2
6        0          0
7        1          1
8        0          0
9        0          0
10       2          2
11       1          1
12       0          0
13       0          0
14       0          0
15       0          0
16       2          2
17       1          1
18       0          0
19       2          2
20       2          2
21       1          1
22       0          0
23       2          2
24       2          2
25       0          0
26       2          2
27       2          2
28       0          0
29       2          1


# MNB

In [11]:
from sklearn.naive_bayes import MultinomialNB
model_MNB=MultinomialNB()

model_MNB.fit(train_x,train_y)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [12]:
prediction_MNB=model_MNB.predict(test_x)


In [13]:
results_MNB=pd.DataFrame({'Prediction':prediction_MNB,'Actual':test_y})
print(results_MNB)


    Actual  Prediction
0        2           1
1        2           1
2        2           1
3        2           1
4        0           0
5        2           1
6        0           0
7        1           1
8        0           0
9        0           0
10       2           1
11       1           1
12       0           0
13       0           0
14       0           0
15       0           0
16       2           1
17       1           1
18       0           0
19       2           1
20       2           1
21       1           1
22       0           0
23       2           1
24       2           1
25       0           0
26       2           1
27       2           1
28       0           0
29       2           1


In [14]:
print(cr(test_y,prediction_MNB))


             precision    recall  f1-score   support

          0       1.00      1.00      1.00        12
          1       0.22      1.00      0.36         4
          2       0.00      0.00      0.00        14

avg / total       0.43      0.53      0.45        30



C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [15]:
print(cm(test_y,prediction_MNB))


[[12  0  0]
 [ 0  4  0]
 [ 0 14  0]]


In [16]:
print(rs(test_y,prediction_MNB)*100)


45.876288659793815
